/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n  fragment FragmentDateTime on DateTime {\n    timestamp\n    timezone\n    offset\n    time\n  }\n":
      TadaDocumentNode<{ timestamp: unknown; timezone: unknown; offset: unknown; time: unknown; }, {}, { fragment: "FragmentDateTime"; on: "DateTime"; masked: true; }>;
    "\n  fragment FragmentFile on File {\n    name\n    url\n    size\n    mime\n    description\n  }\n":
      TadaDocumentNode<{ name: string | null; url: string; size: number; mime: string | null; description: string | null; }, {}, { fragment: "FragmentFile"; on: "File"; masked: true; }>;
    "\n  fragment FragmentImage on Image {\n    url\n    width\n    height\n    alt\n    title\n    size\n    mime\n  }\n":
      TadaDocumentNode<{ url: string; width: number; height: number; alt: string | null; title: string | null; size: number; mime: string | null; }, {}, { fragment: "FragmentImage"; on: "Image"; masked: true; }>;
    "\n  fragment FragmentLanguage on Language {\n    id\n    name\n    direction\n  }\n":
      TadaDocumentNode<{ id: string | null; name: string | null; direction: string | null; }, {}, { fragment: "FragmentLanguage"; on: "Language"; masked: true; }>;
    "\n  fragment FragmentLink on Link {\n    title\n    url\n    internal\n  }\n":
      TadaDocumentNode<{ title: string | null; url: string | null; internal: boolean; }, {}, { fragment: "FragmentLink"; on: "Link"; masked: true; }>;
    "\n  fragment FragmentTextSummary on TextSummary {\n    value\n    processed\n    format\n    summary\n  }\n":
      TadaDocumentNode<{ value: string | null; processed: unknown; format: string | null; summary: unknown; }, {}, { fragment: "FragmentTextSummary"; on: "TextSummary"; masked: true; }>;
    "\n  fragment FragmentText on Text {\n    value\n    processed\n    format\n  }\n":
      TadaDocumentNode<{ value: string | null; processed: unknown; format: string | null; }, {}, { fragment: "FragmentText"; on: "Text"; masked: true; }>;
    "\n    fragment FragmentTermMediaTags on TermMediaTags {\n      id\n      changed {\n        ...FragmentDateTime\n      }\n      description {\n        ...FragmentText\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      name\n      path\n      status\n      weight\n    }\n  ":
      TadaDocumentNode<{ id: string; changed: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; description: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; name: string; path: string; status: boolean; weight: number; }, {}, { fragment: "FragmentTermMediaTags"; on: "TermMediaTags"; masked: true; }>;
    "\n    fragment FragmentMediaFile on MediaFile {\n      id\n      changed {\n        ...FragmentDateTime\n      }\n      created {\n        ...FragmentDateTime\n      }\n      description {\n        ...FragmentText\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      mediaFile {\n        ...FragmentFile\n      }\n      name\n      path\n      status\n      tags {\n        ...FragmentTermMediaTags\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; changed: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; description: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; } | null; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; mediaFile: { [$tada.fragmentRefs]: { FragmentFile: "File"; }; }; name: string; path: string; status: boolean; tags: { [$tada.fragmentRefs]: { FragmentTermMediaTags: "TermMediaTags"; }; }[] | null; }, {}, { fragment: "FragmentMediaFile"; on: "MediaFile"; masked: true; }>;
    "\n    fragment FragmentMediaImage on MediaImage {\n      id\n      caption\n      changed {\n        ...FragmentDateTime\n      }\n      copyright\n      created {\n        ...FragmentDateTime\n      }\n      description {\n        ...FragmentText\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      mediaImage {\n        ...FragmentImage\n      }\n      name\n      path\n      status\n      tags {\n        ...FragmentTermMediaTags\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; caption: string | null; changed: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; copyright: string | null; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; description: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; } | null; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; mediaImage: { [$tada.fragmentRefs]: { FragmentImage: "Image"; }; }; name: string; path: string; status: boolean; tags: { [$tada.fragmentRefs]: { FragmentTermMediaTags: "TermMediaTags"; }; }[] | null; }, {}, { fragment: "FragmentMediaImage"; on: "MediaImage"; masked: true; }>;
    "\n    fragment FragmentMediaVideo on MediaVideo {\n      id\n      caption\n      changed {\n        ...FragmentDateTime\n      }\n      copyright\n      created {\n        ...FragmentDateTime\n      }\n      description {\n        ...FragmentText\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      mediaOembedVideo\n      name\n      path\n      status\n      tags {\n        ...FragmentTermMediaTags\n      }\n      transcript {\n        ...FragmentLink\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; caption: string | null; changed: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; copyright: string | null; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; description: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; } | null; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; mediaOembedVideo: string; name: string; path: string; status: boolean; tags: { [$tada.fragmentRefs]: { FragmentTermMediaTags: "TermMediaTags"; }; }[] | null; transcript: { [$tada.fragmentRefs]: { FragmentLink: "Link"; }; } | null; }, {}, { fragment: "FragmentMediaVideo"; on: "MediaVideo"; masked: true; }>;
    "\n    fragment FragmentMediaUnion on MediaUnion {\n      ...FragmentMediaFile\n      ...FragmentMediaImage\n      ...FragmentMediaVideo\n    }\n  ":
      TadaDocumentNode<{ __typename?: "MediaFile" | undefined; [$tada.fragmentRefs]: { FragmentMediaFile: "Undefined Fragment"; }; } | { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { FragmentMediaFile: "Undefined Fragment"; } & { FragmentMediaImage: "MediaImage"; }; } | { __typename?: "MediaVideo" | undefined; [$tada.fragmentRefs]: { FragmentMediaFile: "Undefined Fragment"; } & { FragmentMediaVideo: "MediaVideo"; }; }, {}, { fragment: "FragmentMediaUnion"; on: "MediaUnion"; masked: true; }>;
    "\n  fragment FragmentRouteExternal on RouteExternal {\n    url\n    internal\n  }\n":
      TadaDocumentNode<{ url: string; internal: boolean; }, {}, { fragment: "FragmentRouteExternal"; on: "RouteExternal"; masked: true; }>;
    "\n    fragment FragmentParagraphImage on ParagraphImage {\n      id\n      created {\n        ...FragmentDateTime\n      }\n      image {\n        ...FragmentMediaImage\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      status\n    }\n  ":
      TadaDocumentNode<{ id: string; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; image: { [$tada.fragmentRefs]: { FragmentMediaImage: "MediaImage"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; status: boolean; }, {}, { fragment: "FragmentParagraphImage"; on: "ParagraphImage"; masked: true; }>;
    "\n    fragment FragmentParagraphText on ParagraphText {\n      id\n      created {\n        ...FragmentDateTime\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      status\n      text {\n        ...FragmentText\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; status: boolean; text: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; }; }, {}, { fragment: "FragmentParagraphText"; on: "ParagraphText"; masked: true; }>;
    "\n    fragment FragmentParagraphTextWithMediaMediaUnion on ParagraphTextWithMediaMediaUnion {\n      ...FragmentMediaImage\n      ...FragmentMediaVideo\n    }\n  ":
      TadaDocumentNode<{ __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { FragmentMediaImage: "MediaImage"; }; } | { __typename?: "MediaVideo" | undefined; [$tada.fragmentRefs]: { FragmentMediaVideo: "MediaVideo"; }; }, {}, { fragment: "FragmentParagraphTextWithMediaMediaUnion"; on: "ParagraphTextWithMediaMediaUnion"; masked: true; }>;
    "\n    fragment FragmentParagraphTextWithMedia on ParagraphTextWithMedia {\n      id\n      created {\n        ...FragmentDateTime\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      media {\n        ...FragmentParagraphTextWithMediaMediaUnion\n      }\n      mediaAlignment\n      status\n      text {\n        ...FragmentText\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; media: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { FragmentParagraphTextWithMediaMediaUnion: "ParagraphTextWithMediaMediaUnion"; }; } | { __typename?: "MediaVideo" | undefined; [$tada.fragmentRefs]: { FragmentParagraphTextWithMediaMediaUnion: "ParagraphTextWithMediaMediaUnion"; }; }; mediaAlignment: string; status: boolean; text: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; }; }, {}, { fragment: "FragmentParagraphTextWithMedia"; on: "ParagraphTextWithMedia"; masked: true; }>;
    "\n    fragment FragmentParagraphVideo on ParagraphVideo {\n      id\n      created {\n        ...FragmentDateTime\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      status\n      video {\n        ...FragmentMediaVideo\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; status: boolean; video: { [$tada.fragmentRefs]: { FragmentMediaVideo: "MediaVideo"; }; }; }, {}, { fragment: "FragmentParagraphVideo"; on: "ParagraphVideo"; masked: true; }>;
    "\n    fragment FragmentNodePageContentUnion on NodePageContentUnion {\n      ...FragmentParagraphImage\n      ...FragmentParagraphText\n      ...FragmentParagraphTextWithMedia\n      ...FragmentParagraphVideo\n    }\n  ":
      TadaDocumentNode<{ __typename?: "ParagraphImage" | undefined; [$tada.fragmentRefs]: { FragmentParagraphImage: "ParagraphImage"; }; } | { __typename?: "ParagraphText" | undefined; [$tada.fragmentRefs]: { FragmentParagraphText: "ParagraphText"; }; } | { __typename?: "ParagraphTextWithMedia" | undefined; [$tada.fragmentRefs]: { FragmentParagraphTextWithMedia: "ParagraphTextWithMedia"; }; } | { __typename?: "ParagraphVideo" | undefined; [$tada.fragmentRefs]: { FragmentParagraphVideo: "ParagraphVideo"; }; }, {}, { fragment: "FragmentNodePageContentUnion"; on: "NodePageContentUnion"; masked: true; }>;
    "\n    fragment FragmentNodePage on NodePage {\n      __typename\n      id\n      changed {\n        ...FragmentDateTime\n      }\n      content {\n        ...FragmentNodePageContentUnion\n      }\n      created {\n        ...FragmentDateTime\n      }\n      langcode {\n        ...FragmentLanguage\n      }\n      path\n      promote\n      publishedAt {\n        ...FragmentDateTime\n      }\n      seoTitle\n      status\n      sticky\n      teaserMedia {\n        ...FragmentMediaImage\n      }\n      teaserText\n      text {\n        ...FragmentText\n      }\n      title\n    }\n  ":
      TadaDocumentNode<{ __typename: "NodePage"; id: string; changed: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; content: ({ __typename?: "ParagraphImage" | undefined; [$tada.fragmentRefs]: { FragmentNodePageContentUnion: "NodePageContentUnion"; }; } | { __typename?: "ParagraphText" | undefined; [$tada.fragmentRefs]: { FragmentNodePageContentUnion: "NodePageContentUnion"; }; } | { __typename?: "ParagraphTextWithMedia" | undefined; [$tada.fragmentRefs]: { FragmentNodePageContentUnion: "NodePageContentUnion"; }; } | { __typename?: "ParagraphVideo" | undefined; [$tada.fragmentRefs]: { FragmentNodePageContentUnion: "NodePageContentUnion"; }; })[]; created: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; path: string; promote: boolean; publishedAt: { [$tada.fragmentRefs]: { FragmentDateTime: "DateTime"; }; }; seoTitle: string; status: boolean; sticky: boolean; teaserMedia: { [$tada.fragmentRefs]: { FragmentMediaImage: "MediaImage"; }; } | null; teaserText: string | null; text: { [$tada.fragmentRefs]: { FragmentText: "Text"; }; } | null; title: string; }, {}, { fragment: "FragmentNodePage"; on: "NodePage"; masked: true; }>;
    "\n    fragment FragmentRouteEntityUnion on RouteEntityUnion {\n      ...FragmentNodePage\n    }\n  ":
      TadaDocumentNode<{ __typename?: "NodePage" | undefined; [$tada.fragmentRefs]: { FragmentNodePage: "NodePage"; }; }, {}, { fragment: "FragmentRouteEntityUnion"; on: "RouteEntityUnion"; masked: true; }>;
    "\n    fragment FragmentRouteInternal on RouteInternal {\n      url\n      internal\n      breadcrumbs {\n        ...FragmentLink\n      }\n      entity {\n        ...FragmentRouteEntityUnion\n      }\n    }\n  ":
      TadaDocumentNode<{ url: string; internal: boolean; breadcrumbs: { [$tada.fragmentRefs]: { FragmentLink: "Link"; }; }[] | null; entity: { __typename?: "NodePage" | undefined; [$tada.fragmentRefs]: { FragmentRouteEntityUnion: "RouteEntityUnion"; }; } | null; }, {}, { fragment: "FragmentRouteInternal"; on: "RouteInternal"; masked: true; }>;
    "\n    fragment FragmentRouteUnion on RouteUnion {\n      ...FragmentRouteInternal\n      ...FragmentRouteExternal\n    }\n  ":
      TadaDocumentNode<{ __typename?: "RouteExternal" | undefined; [$tada.fragmentRefs]: { FragmentRouteExternal: "RouteExternal"; }; } | { __typename?: "RouteInternal" | undefined; [$tada.fragmentRefs]: { FragmentRouteInternal: "RouteInternal"; }; }, {}, { fragment: "FragmentRouteUnion"; on: "RouteUnion"; masked: true; }>;
    "\n  fragment FragmentMenuItemAttributes on MenuItemAttributes {\n    class\n  }\n":
      TadaDocumentNode<{ class: string | null; }, {}, { fragment: "FragmentMenuItemAttributes"; on: "MenuItemAttributes"; masked: true; }>;
    "\n    fragment FragmentMenuItem on MenuItem {\n      id\n      title\n      description\n      url\n      langcode {\n        ...FragmentLanguage\n      }\n      internal\n      expanded\n      attributes {\n        ...FragmentMenuItemAttributes\n      }\n      children {\n        id\n        title\n        description\n        url\n        internal\n      }\n      route {\n        ...FragmentRouteUnion\n      }\n    }\n  ":
      TadaDocumentNode<{ id: string; title: string; description: string | null; url: string | null; langcode: { [$tada.fragmentRefs]: { FragmentLanguage: "Language"; }; }; internal: boolean; expanded: boolean; attributes: { [$tada.fragmentRefs]: { FragmentMenuItemAttributes: "MenuItemAttributes"; }; }; children: { id: string; title: string; description: string | null; url: string | null; internal: boolean; }[]; route: { __typename?: "RouteExternal" | undefined; [$tada.fragmentRefs]: { FragmentRouteUnion: "RouteUnion"; }; } | { __typename?: "RouteInternal" | undefined; [$tada.fragmentRefs]: { FragmentRouteUnion: "RouteUnion"; }; } | null; }, {}, { fragment: "FragmentMenuItem"; on: "MenuItem"; masked: true; }>;
    "\n    fragment FragmentMenu on Menu {\n      id\n      items {\n        ...FragmentMenuItem\n      }\n      name\n    }\n  ":
      TadaDocumentNode<{ id: string; items: { [$tada.fragmentRefs]: { FragmentMenuItem: "MenuItem"; }; }[]; name: string; }, {}, { fragment: "FragmentMenu"; on: "Menu"; masked: true; }>;
    "\n    fragment FragmentMenuUnion on MenuUnion {\n      ...FragmentMenu\n    }\n  ":
      TadaDocumentNode<{ __typename?: "Menu" | undefined; [$tada.fragmentRefs]: { FragmentMenu: "Menu"; }; }, {}, { fragment: "FragmentMenuUnion"; on: "MenuUnion"; masked: true; }>;
    "\n    fragment FragmentNodeUnion on NodeUnion {\n      ...FragmentNodePage\n    }\n  ":
      TadaDocumentNode<{ __typename?: "NodePage" | undefined; [$tada.fragmentRefs]: { FragmentNodePage: "NodePage"; }; }, {}, { fragment: "FragmentNodeUnion"; on: "NodeUnion"; masked: true; }>;
    "\n    fragment FragmentParagraphUnion on ParagraphUnion {\n      ...FragmentParagraphImage\n      ...FragmentParagraphText\n      ...FragmentParagraphTextWithMedia\n      ...FragmentParagraphVideo\n    }\n  ":
      TadaDocumentNode<{ __typename?: "ParagraphImage" | undefined; [$tada.fragmentRefs]: { FragmentParagraphImage: "ParagraphImage"; }; } | { __typename?: "ParagraphText" | undefined; [$tada.fragmentRefs]: { FragmentParagraphText: "ParagraphText"; }; } | { __typename?: "ParagraphTextWithMedia" | undefined; [$tada.fragmentRefs]: { FragmentParagraphTextWithMedia: "ParagraphTextWithMedia"; }; } | { __typename?: "ParagraphVideo" | undefined; [$tada.fragmentRefs]: { FragmentParagraphVideo: "ParagraphVideo"; }; }, {}, { fragment: "FragmentParagraphUnion"; on: "ParagraphUnion"; masked: true; }>;
    "\n    query RouteQuery($path: String!) {\n      route(path: $path) {\n        __typename\n        ...FragmentRouteUnion\n      }\n    }\n  ":
      TadaDocumentNode<{ route: { __typename: "RouteExternal"; [$tada.fragmentRefs]: { FragmentRouteUnion: "RouteUnion"; }; } | { __typename: "RouteInternal"; [$tada.fragmentRefs]: { FragmentRouteUnion: "RouteUnion"; }; } | null; }, { path: string; }, void>;
  }
}
